### ISSUE TITLE
Quantum support

### ISSUE THREAD

**Issue by HaleTom** [guyzmo/FFTabsOutliner#2]
Heya, thanks for the work you put in on this!

Any plans to update for Firefox Quantum?

**Comment by ShervinM** [comment]
@HaleTom 
This project has been inactive (besides a few initial weeks around early 2013). wish someone with plugin development knowledge would pick it up, it's a shame really...considering how useful the chrome version is...
actually the original tabsoutliner developer on chrome has also gone inactive. a new developer is slowly working on a more reliable clone, still a long way away though
https://github.com/cxw42/TabFern

**Comment by HaleTom** [comment]
Thanks for the info, and the work you did on this!

**Comment by 7vq** [comment]
> a new developer is slowly working on a more reliable clone, still a long way away though
https://github.com/cxw42/TabFern

I just tested it, and it now looks extremely close to ready for Firefox: https://github.com/cxw42/TabFern/issues/100#issuecomment-1015042960
